site_name: OpenAI Agents SDK
theme:
    name: material
    features:
        # Allows copying code blocks
        - content.code.copy
        # Allows selecting code blocks
        - content.code.select
        # Shows the current path in the sidebar
        - navigation.path
        # Shows sections in the sidebar
        - navigation.sections
        # Shows sections expanded by default
        - navigation.expand
        # Enables annotations in code blocks
        - content.code.annotate
    palette:
        primary: black
    logo: assets/logo.svg
    favicon: images/favicon-platform.svg
nav:
    - Intro: index.md
    - Quickstart: quickstart.md
    - Documentation:
          - agents.md
          - running_agents.md
          - results.md
          - streaming.md
          - tools.md
          - handoffs.md
          - tracing.md
          - context.md
          - guardrails.md
          - multi_agent.md
          - models.md
          - config.md
    - API Reference:
          - Agents:
                - ref/index.md
                - ref/agent.md
                - ref/run.md
                - ref/tool.md
                - ref/result.md
                - ref/stream_events.md
                - ref/handoffs.md
                - ref/lifecycle.md
                - ref/items.md
                - ref/run_context.md
                - ref/usage.md
                - ref/exceptions.md
                - ref/guardrail.md
                - ref/model_settings.md
                - ref/agent_output.md
                - ref/function_schema.md
                - ref/models/interface.md
                - ref/models/openai_chatcompletions.md
                - ref/models/openai_responses.md
          - Tracing:
                - ref/tracing/index.md
                - ref/tracing/create.md
                - ref/tracing/traces.md
                - ref/tracing/spans.md
                - ref/tracing/processor_interface.md
                - ref/tracing/processors.md
                - ref/tracing/scope.md
                - ref/tracing/setup.md
                - ref/tracing/span_data.md
                - ref/tracing/util.md
          - Extensions:
                - ref/extensions/handoff_filters.md
                - ref/extensions/handoff_prompt.md

plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: ["src/agents"]
                  selection:
                      docstring_style: google
                  options:
                      # Shows links to other members in signatures
                      signature_crossrefs: true
                      # Orders members by source order, rather than alphabetical
                      members_order: source
                      # Puts the signature on a separate line from the member name
                      separate_signature: true
                      # Shows type annotations in signatures
                      show_signature_annotations: true
                      # Makes the font sizes nicer
                      heading_level: 3

extra:
    # Remove material generation message in footer
    generator: false

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

validation:
    omitted_files: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn

extra_css:
    - stylesheets/extra.css

watch:
    - "src/agents"
